server:
  port: 8301
spring:
  application:
    name: ribbon-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://tongye:123456@localhost:8001/eureka/ #配置注册中心地址
service-url:
  user-service: http://user-service
